### ISSUE TITLE
Status tab is not migrated to new admin v7

### ISSUE THREAD

**Issue by TA2k** [iobroker-community-adapters/ioBroker.acme#116]
<img width="1166" alt="image" src="https://github.com/iobroker-community-adapters/ioBroker.acme/assets/1307684/a88aec5e-57ed-4531-8d21-1af906caf004">

Same issue like
https://github.com/ioBroker/ioBroker.parser/issues/244

**Comment by mcm1957** [comment]
Eventually fixed by https://github.com/iobroker-community-adapters/ioBroker.acme/pull/115

**Comment by peterbaumert** [comment]
> Eventually fixed by #115

that did not fix the issue for me:

![image](https://github.com/iobroker-community-adapters/ioBroker.acme/assets/1212934/8375b9a0-5101-42ac-81dc-023cafda99fb)

**Comment by mcm1957** [comment]
Just to be sure
Did you try to clear the Browser Cache?

**Comment by peterbaumert** [comment]
> @peterbaumert
> 
> Just to be sure Did you try to clear the Browser Cache?

Yes, even tried with a browser I never even used before. Same picture.

**Comment by raintonr** [comment]
Same here. In fact, a hard browser refresh changes the error for me, now reads:

> Cannot import from custom/customComponents.js: TypeError: Class extends value undefined is not a constructor or null

**Comment by raintonr** [comment]
JSONconfig is nice, but if it could not provide the required solution, should have been enhanced to do so.

I didn't write the code for that tab and don't agree with how it was implemented, and therefore don't want to get involved in its maintenance.

**Comment by mcm1957** [comment]
OK, thanks for feedback. I'll remove the maintainers tag in this case.

**Comment by mcm1957** [comment]
fied with 1.0.3
